name = "cargo"
subteam-of = "devtools"

[people]
leads = ["ehuss"]
members = [
    "Eh2406",
    "ehuss",
    "joshtriplett",
    "weihanglo",
    "epage",
    "Muscraft",
    "arlosi"
]
alumni = [
    "alexcrichton",
    "nrc",
    "dwijnand",
    "wycats",
    "withoutboats",
]

[permissions]
bors.rust.review = true
bors.cargo.review = true

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[rfcbot]
label = "T-cargo"
name = "Cargo"
ping = "rust-lang/cargo"

[website]
name = "Cargo team"
description = "Designing and implementing the official Rust package manager, Cargo"
zulip-stream = "t-cargo"

[[lists]]
address = "cargo@rust-lang.org"

[[zulip-groups]]
name = "T-cargo"
