name = "leads"
kind = "marker-team"

[people]
leads = []
members = []
include-team-leads = true

[[github]]
orgs = ["rust-lang"]

[[lists]]
address = "leads@rust-lang.org"
extra-teams = ["wg-leads", "core"]
