name = "web-presence"
subteam-of = "launching-pad"

[people]
leads = []
members = []
alumni = []

[[lists]]
address = "web-presence@rust-lang.org"
extra-teams = [
    "crates-io",
    "docs-rs",
]
extra-people = [
    "Manishearth",
    "skade",
    "shepmaster",
    "pichfl",
]
