name = "wg-secure-code"
subteam-of = "launching-pad"
kind = "working-group"

[people]
leads = ["Shnatsel", "tarcieri"]
members = [
    "Shnatsel",
    "tarcieri",
    "alex",
    "amousset",
]
alumni = [
    "danielhenrymantilla",
    "joshlf",
    "pinkforest",
    "stusmall",
    "xacrimon",
]

[[github]]
team-name = "wg-secure-code"
orgs = ["rust-lang"]

[website]
name = "Secure Code working group"
description = "Making it easy to write secure code in Rust"
repo = "https://github.com/rust-secure-code/wg"
zulip-stream = "wg-secure-code"

[[lists]]
address = "secure-code-wg@rust-lang.org"

[[zulip-groups]]
name = "WG-secure-code"
