org = "rust-lang"
name = "areweasyncyet.rs"
description = "Are we async yet?"
homepage = "https://areweasyncyet.rs"
bots = []

[access.teams]
wg-async = "write"

[access.individuals]
upsuper = "write"
