org = "rust-lang"
name = "async-fundamentals-initiative"
description = ""
homepage = "https://rust-lang.github.io/async-fundamentals-initiative/"
bots = []

[access.teams]
wg-async = "maintain"

[[branch-protections]]
pattern = "master"
required-approvals = 0
