org = "rust-lang"
name = "edition-guide"
description = "A guide to changes between various editions of Rust"
homepage = "https://doc.rust-lang.org/stable/edition-guide/"
bots = ["rustbot", "rfcbot"]

[access.teams]
project-edition-2024 = "maintain"
