org = "rust-lang"
name = "generic-associated-types-initiative"
description = "Generic Associated Types lang team initiative"
homepage = "https://rust-lang.github.io/generic-associated-types-initiative/"
bots = []

[access.teams]
initiative-generic-associated-types = "write"
