org = "rust-lang"
name = "git2-rs"
description = "libgit2 bindings for Rust"
homepage = "https://docs.rs/git2"
bots = ["rustbot"]

[access.teams]
cargo = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["Success gate"]
required-approvals = 0
