org = 'rust-lang'
name = 'glob'
description = 'Support for matching file paths against Unix shell style patterns.'
homepage = "http://doc.rust-lang.org/glob"
bots = []

[access.teams]
crate-maintainers = 'maintain'
