org = "rust-lang"
name = "hashbrown"
description = "Rust port of Google's SwissTable hash map"
homepage = "https://rust-lang.github.io/hashbrown"
bots = ["bors"]

[access.teams]
libs = "write"
libs-contributors = "write"

[[branch-protections]]
pattern = "master"
