org = "rust-lang"
name = "impl-trait-initiative"
description = "Impl trait lang team initiative"
homepage = "https://rust-lang.github.io/impl-trait-initiative/"
bots = []

[access.teams]
initiative-impl-trait = "maintain"
