org = 'rust-lang'
name = 'libc'
description = 'Raw bindings to platform APIs for Rust'
homepage = "https://docs.rs/libc"
bots = [
    'rustbot',
]

[access.teams]
crate-maintainers = 'maintain'

[[branch-protections]]
pattern = 'main'
ci-checks = ['success']
required-approvals = 0

[[branch-protections]]
pattern = 'libc-0.2'
ci-checks = ['success']
required-approvals = 0
