org = "rust-lang"
name = "libtest-next"
description = "T-testing-devex experiments for new testing tools for Rust developers"
homepage = "https://docs.rs/pytest-rs"
bots = ["rustbot", "rfcbot"]

[access.teams]
testing-devex = "write"
