org = 'rust-lang'
name = 'log'
description = 'Logging implementation for Rust'
homepage = "https://docs.rs/log"
bots = []

[access.teams]
crate-maintainers = 'maintain'

[access.individuals]
Thomasdezeeuw = 'maintain'
