org = "rust-lang"
name = "mdBook"
description = "Create book from markdown files. Like Gitbook but implemented in Rust"
bots = ["rustbot"]

[access.teams]
devtools = "write"

[access.individuals]
# Dylan-DPC is maintaining mdbook along with ehuss. Planning to add a team
# soon, and then this can be removed.
Dylan-DPC = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["Success gate"]
required-approvals = 0
