org = "rust-lang"
name = "packed_simd"
description = "Portable Packed SIMD Vectors for Rust standard library"
homepage = "https://rust-lang.github.io/packed_simd/packed_simd_2/"
bots = []

[access.teams]
libs-contributors = "write"
libs-api = "write"
libs = "write"
project-portable-simd = "write"
