org = "rust-lang"
name = "regex"
description = "An implementation of regular expressions for Rust. This implementation uses finite automata and guarantees linear time matching on all inputs."
homepage = "https://docs.rs/regex"
bots = []

[access.teams]
regex = "maintain"
