org = "rust-lang"
name = "rust-bindgen"
description = "Automatically generates Rust FFI bindings to C (and some C++) libraries."
homepage = "https://rust-lang.github.io/rust-bindgen/"
bots = ["rustbot"]

[access.teams]
wg-bindgen = "write"

[[branch-protections]]
pattern = "main"
required-approvals = 0
ci-checks = ["success"]
