org = "rust-lang"
name = "rust-playground"
description = "The Rust Playground"
homepage = "https://play.rust-lang.org/"
bots = []

[access.teams]
infra = "maintain"

[[branch-protections]]
pattern = "main"
ci-checks = []
required-approvals = 0
