org = "rust-lang"
name = "rustc-pr-tracking"
description = "Statistics about PRs on the rustc repository."
homepage = "https://rust-lang.github.io/rustc-pr-tracking/"
bots = ["highfive"]

[access.teams]
release = "write"
