org = 'rust-lang'
name = 'triagebot'
description = 'Automation/tooling for Rust spaces'
homepage = "https://triage.rust-lang.org"
bots = ["rustbot"]

[access.teams]
infra = "maintain"
triagebot = "maintain"

[[branch-protections]]
pattern = "master"
