org = "rust-lang"
name = "types-team"
description = "Home of the \"types team\", affiliated with the compiler and lang teams."
homepage = "https://rust-lang.github.io/types-team/"
bots = ["rustbot"]

[access.teams]
types = "write"
