org = "rust-lang"
name = "wg-async"
description = "Working group dedicated to improving the foundations of Async I/O in Rust"
homepage = "https://rust-lang.github.io/wg-async/"
bots = ["rustbot"]

[access.teams]
wg-async = "write"

[[branch-protections]]
pattern = "master"
required-approvals = 0
